export type Locale = 'en' | 'es' | 'it';

const es: Record<string, string> = {
  'Home': 'Inicio', 'Work': 'Proyectos', 'Services': 'Servicios', 'Process': 'Proceso', 'Contact': 'Contacto',
  'Open menu': 'Abrir menú', 'Close menu': 'Cerrar menú', 'Start a project': 'Iniciar un proyecto', 'Skip to content': 'Ir al contenido',
  'DIGITAL DESIGN & DEVELOPMENT STUDIO': 'ESTUDIO DE DISEÑO Y DESARROLLO DIGITAL',
  'Websites,': 'Sitios,', 'stores, and': 'tiendas y', 'systems': 'sistemas', 'built': 'creados', 'around your': 'para tu', 'business.': 'negocio.',
  'Custom design. Purpose-built technology.': 'Diseño a medida. Tecnología con propósito.', 'Digital experiences that turn interest into action.': 'Experiencias digitales que convierten interés en acción.',
  'View selected work': 'Ver proyectos', 'MADE FOR YOUR BUSINESS.': 'HECHO PARA TU NEGOCIO.', 'BUILT TO PERFORM.': 'CREADO PARA RENDIR.', 'DESIGN × TECHNOLOGY': 'DISEÑO × TECNOLOGÍA', '01 — PURPOSE-BUILT DIGITAL PRODUCTS': '01 — PRODUCTOS DIGITALES A MEDIDA', 'Thoughtful from the first pixel.': 'Pensado desde el primer píxel.', 'Explore NADAV': 'Conocé NADAV',
  'WHAT WE BUILD': 'LO QUE CREAMOS', 'E-commerce': 'E-commerce', 'Booking & ordering': 'Reservas y pedidos', 'Business software': 'Software para empresas',
  '01 / OUR APPROACH': '01 / NUESTRO ENFOQUE', 'Not another template.': 'No es otra plantilla.', 'A digital product built': 'Un producto digital creado', 'around your business.': 'alrededor de tu negocio.',
  'A strong website does more than look good. It helps people understand, decide, book, order, or buy. NADAV combines strategy, design, and custom development to make those actions feel simple.': 'Un buen sitio hace más que verse bien. Ayuda a entender, decidir, reservar, pedir o comprar. En NADAV combinamos estrategia, diseño y desarrollo a medida para que esas acciones sean simples.',
  '02 / SELECTED WORK': '02 / PROYECTOS', 'Products with a job to do': 'Productos con un trabajo claro', 'NADAV products and custom work across service, retail, and hospitality businesses.': 'Productos NADAV y proyectos a medida para negocios de servicios, retail y hospitalidad.', 'View project': 'Ver proyecto', 'Ask about this project': 'Consultar por este proyecto',
  '03 / WHAT WE DO': '03 / LO QUE HACEMOS', 'One partner for the website': 'Un solo equipo para el sitio', 'and the system behind it.': 'y el sistema que lo impulsa.', 'Clear customer experiences.': 'Experiencias claras para tus clientes.', 'Practical tools for your team.': 'Herramientas prácticas para tu equipo.',
  '04 / HOW WE WORK': '04 / CÓMO TRABAJAMOS', 'From business': 'De una necesidad', 'need to working': 'del negocio a un', 'product.': 'producto real.', 'A clear process.': 'Un proceso claro.', 'Direct communication.': 'Comunicación directa.', 'No mystery between idea and launch.': 'Sin misterios entre la idea y el lanzamiento.', 'Tell us what you need': 'Contanos qué necesitás',
  'Discovery': 'Descubrimiento', 'Direction': 'Dirección', 'Design': 'Diseño', 'Development': 'Desarrollo', 'Launch': 'Lanzamiento',
  'We learn how your business works, who you need to reach, and what the product needs to accomplish.': 'Entendemos cómo funciona tu negocio, a quién necesitás llegar y qué debe lograr el producto.', 'We define the structure, priorities, functionality, and clearest path for your customers.': 'Definimos la estructura, las prioridades, las funciones y el camino más claro para tus clientes.', 'We create a visual system and user experience that feels specific to your business.': 'Creamos un sistema visual y una experiencia específica para tu negocio.', 'We turn the approved direction into a fast, responsive, dependable product.': 'Convertimos la dirección aprobada en un producto rápido, adaptable y confiable.', 'We test the complete experience, launch it, and make sure your team knows what comes next.': 'Probamos la experiencia completa, publicamos y dejamos claros los próximos pasos para tu equipo.',
  '05 / START A CONVERSATION': '05 / EMPECEMOS A HABLAR', 'Have a project?': '¿Tenés un proyecto?', 'Let’s make it': 'Hagámoslo', 'useful.': 'útil.', 'Tell us what you need, what is not working, or what you want to launch. We’ll review it and follow up by email.': 'Contanos qué necesitás, qué no está funcionando o qué querés lanzar. Lo revisaremos y te responderemos por email.', 'Email NADAV': 'Escribir a NADAV', 'Good work starts with': 'Un buen trabajo empieza con', 'a clear conversation.': 'una conversación clara.',
  'Tell us about your project.': 'Contanos sobre tu proyecto.', 'Name *': 'Nombre *', 'Your name': 'Tu nombre', 'Company': 'Empresa', 'Company or organization': 'Empresa u organización', 'Work email *': 'Email laboral *', 'Phone (optional)': 'Teléfono (opcional)', 'Project type *': 'Tipo de proyecto *', 'What do you need?': '¿Qué necesitás?', 'Estimated budget (USD) *': 'Presupuesto estimado (USD) *', 'Estimated project budget in US dollars': 'Presupuesto estimado del proyecto en dólares estadounidenses', 'Choose a range': 'Elegí un rango', 'Project details *': 'Detalles del proyecto *', 'What are you building, improving, or replacing?': '¿Qué querés crear, mejorar o reemplazar?', 'Current website': 'Sitio actual', 'We only use your information to respond to this inquiry.': 'Solo usamos tus datos para responder esta consulta.', 'Sending…': 'Enviando…', 'Send project inquiry': 'Enviar consulta',
  'Custom digital products, designed with purpose.': 'Productos digitales a medida, diseñados con propósito.', 'Back to top': 'Volver arriba', 'All rights reserved.': 'Todos los derechos reservados.', 'Privacy': 'Privacidad', 'Terms': 'Términos', 'Legal links': 'Enlaces legales',
  'Hi! I’m NADAV’s automated assistant. What are you looking to build?': '¡Hola! Soy el asistente automático de NADAV. ¿Qué te gustaría crear?', 'Open NADAV Assistant': 'Abrir el asistente de NADAV', 'Automated FAQ assistant · Available anytime': 'Asistente automático · Disponible siempre', 'Contact the team': 'Contactar al equipo', 'Type your question': 'Escribí tu consulta', 'Type your question…': 'Escribí tu consulta…', 'Send message': 'Enviar mensaje', 'Go to contact': 'Ir a contacto',
  'Choose a project type and estimated budget.': 'Elegí un tipo de proyecto y un presupuesto estimado.', 'We could not send your inquiry. Please try again.': 'No pudimos enviar tu consulta. Intentá nuevamente.', 'Thank you—your inquiry is in. We’ll follow up by email.': 'Gracias, recibimos tu consulta. Te responderemos por email.', 'We could not connect. Check your connection and try again.': 'No pudimos conectar. Revisá tu conexión e intentá nuevamente.', 'Please complete this field.': 'Completá este campo.', 'Enter a valid email address.': 'Ingresá un email válido.', 'Enter a valid phone number.': 'Ingresá un teléfono válido.',
  'Not sure yet': 'Todavía no estoy seguro', 'WhatsApp is not available right now. Send your inquiry through the form or email us at {email}.': 'WhatsApp no está disponible en este momento. Enviá tu consulta desde el formulario o escribinos a {email}.',
  'Custom websites': 'Sitios web a medida', 'Fast, focused websites built around your business, customers, and goals.': 'Sitios rápidos y enfocados en tu negocio, tus clientes y tus objetivos.', 'Online stores with the catalog, checkout, payments, and management tools you need.': 'Tiendas online con catálogo, checkout, pagos y herramientas de gestión.', 'Booking systems': 'Sistemas de reservas', 'Branded scheduling experiences for services, staff, availability, and appointments.': 'Reservas con tu marca para servicios, equipo, disponibilidad y turnos.', 'Restaurant ordering': 'Pedidos para restaurantes', 'Custom menus and ordering flows for pickup, delivery, and restaurant operations.': 'Menús y pedidos a medida para retiro, delivery y operación diaria.', 'Dashboards, workflows, and internal tools shaped around how your team works.': 'Paneles, flujos y herramientas internas adaptadas a tu equipo.', 'Optimization & support': 'Optimización y soporte', 'Ongoing improvements, maintenance, and technical support after launch.': 'Mejoras, mantenimiento y soporte técnico después del lanzamiento.',
  'Booking platform · Custom websites': 'Plataforma de reservas · Sitios a medida', 'A custom website and booking experience with services, staff, live availability, appointment scheduling, and business-specific demos.': 'Un sitio y una experiencia de reservas a medida con servicios, profesionales, disponibilidad, turnos y demos específicas para cada negocio.', 'Restaurant ordering · Operations': 'Pedidos para restaurantes · Operaciones', 'A custom restaurant storefront with menu options, pickup and delivery ordering, stock controls, and tools for managing daily orders.': 'Una tienda gastronómica a medida con opciones de menú, pedidos para retiro o delivery, control de stock y gestión diaria.', 'Food & beverage · E-commerce': 'Gastronomía · E-commerce', 'A bold restaurant experience with an online catalog and a direct path to purchase.': 'Una experiencia gastronómica con identidad fuerte, catálogo online y un camino directo a la compra.', 'Craft & services · Business website': 'Oficios y servicios · Sitio empresarial', 'An editorial business site built to explain services, showcase work, and turn visits into inquiries.': 'Un sitio editorial para explicar servicios, mostrar trabajos y convertir visitas en consultas.', 'Fashion · E-commerce': 'Moda · E-commerce', 'An editorial storefront with products, variants, inventory, and connected administration.': 'Una tienda editorial con productos, variantes, inventario y administración conectada.', 'Hospitality · Editorial website': 'Hospitalidad · Sitio editorial', 'A bilingual hospitality website shaped around story, atmosphere, and a direct path to stay inquiries.': 'Un sitio bilingüe de hospitalidad centrado en la historia, la atmósfera y las consultas de estadía.',
};

const it: Record<string, string> = {
  'Home': 'Home', 'Work': 'Progetti', 'Services': 'Servizi', 'Process': 'Processo', 'Contact': 'Contatti',
  'Open menu': 'Apri menu', 'Close menu': 'Chiudi menu', 'Start a project': 'Avvia un progetto', 'Skip to content': 'Vai al contenuto',
  'DIGITAL DESIGN & DEVELOPMENT STUDIO': 'STUDIO DI DESIGN E SVILUPPO DIGITALE', 'Websites,': 'Siti,', 'stores, and': 'store e', 'systems': 'sistemi', 'built': 'creati', 'around your': 'per la tua', 'business.': 'attività.',
  'Custom design. Purpose-built technology.': 'Design su misura. Tecnologia con uno scopo.', 'Digital experiences that turn interest into action.': 'Esperienze digitali che trasformano l’interesse in azione.', 'View selected work': 'Scopri i progetti', 'MADE FOR YOUR BUSINESS.': 'PENSATO PER LA TUA ATTIVITÀ.', 'BUILT TO PERFORM.': 'CREATO PER FUNZIONARE.', 'DESIGN × TECHNOLOGY': 'DESIGN × TECNOLOGIA', '01 — PURPOSE-BUILT DIGITAL PRODUCTS': '01 — PRODOTTI DIGITALI SU MISURA', 'Thoughtful from the first pixel.': 'Curato fin dal primo pixel.', 'Explore NADAV': 'Scopri NADAV',
  'WHAT WE BUILD': 'COSA REALIZZIAMO', 'E-commerce': 'E-commerce', 'Booking & ordering': 'Prenotazioni e ordini', 'Business software': 'Software aziendale',
  '01 / OUR APPROACH': '01 / IL NOSTRO APPROCCIO', 'Not another template.': 'Non il solito template.', 'A digital product built': 'Un prodotto digitale costruito', 'around your business.': 'intorno alla tua attività.', 'A strong website does more than look good. It helps people understand, decide, book, order, or buy. NADAV combines strategy, design, and custom development to make those actions feel simple.': 'Un buon sito non deve solo essere bello. Deve aiutare le persone a capire, scegliere, prenotare, ordinare o acquistare. NADAV unisce strategia, design e sviluppo su misura per rendere semplici queste azioni.',
  '02 / SELECTED WORK': '02 / PROGETTI', 'Products with a job to do': 'Prodotti con un obiettivo concreto', 'NADAV products and custom work across service, retail, and hospitality businesses.': 'Prodotti NADAV e progetti su misura per servizi, retail e hospitality.', 'View project': 'Vedi progetto', 'Ask about this project': 'Richiedi un progetto simile',
  '03 / WHAT WE DO': '03 / COSA FACCIAMO', 'One partner for the website': 'Un unico partner per il sito', 'and the system behind it.': 'e il sistema che lo supporta.', 'Clear customer experiences.': 'Esperienze chiare per i clienti.', 'Practical tools for your team.': 'Strumenti pratici per il tuo team.',
  '04 / HOW WE WORK': '04 / COME LAVORIAMO', 'From business': 'Da un’esigenza', 'need to working': 'aziendale a un', 'product.': 'prodotto concreto.', 'A clear process.': 'Un processo chiaro.', 'Direct communication.': 'Comunicazione diretta.', 'No mystery between idea and launch.': 'Nessun mistero tra idea e lancio.', 'Tell us what you need': 'Raccontaci cosa ti serve',
  'Discovery': 'Scoperta', 'Direction': 'Direzione', 'Design': 'Design', 'Development': 'Sviluppo', 'Launch': 'Lancio', 'We learn how your business works, who you need to reach, and what the product needs to accomplish.': 'Comprendiamo come funziona la tua attività, chi vuoi raggiungere e cosa deve ottenere il prodotto.', 'We define the structure, priorities, functionality, and clearest path for your customers.': 'Definiamo struttura, priorità, funzioni e il percorso più chiaro per i clienti.', 'We create a visual system and user experience that feels specific to your business.': 'Creiamo un sistema visivo e un’esperienza specifici per la tua attività.', 'We turn the approved direction into a fast, responsive, dependable product.': 'Trasformiamo la direzione approvata in un prodotto veloce, reattivo e affidabile.', 'We test the complete experience, launch it, and make sure your team knows what comes next.': 'Testiamo l’esperienza completa, pubblichiamo e definiamo i passi successivi per il tuo team.',
  '05 / START A CONVERSATION': '05 / INIZIAMO A PARLARE', 'Have a project?': 'Hai un progetto?', 'Let’s make it': 'Rendiamolo', 'useful.': 'utile.', 'Tell us what you need, what is not working, or what you want to launch. We’ll review it and follow up by email.': 'Raccontaci cosa ti serve, cosa non funziona o cosa vuoi lanciare. Lo valuteremo e ti risponderemo via email.', 'Email NADAV': 'Scrivi a NADAV', 'Good work starts with': 'Un buon lavoro nasce da', 'a clear conversation.': 'una conversazione chiara.',
  'Tell us about your project.': 'Raccontaci il tuo progetto.', 'Name *': 'Nome *', 'Your name': 'Il tuo nome', 'Company': 'Azienda', 'Company or organization': 'Azienda o organizzazione', 'Work email *': 'Email di lavoro *', 'Phone (optional)': 'Telefono (facoltativo)', 'Project type *': 'Tipo di progetto *', 'What do you need?': 'Di cosa hai bisogno?', 'Estimated budget (USD) *': 'Budget stimato (USD) *', 'Estimated project budget in US dollars': 'Budget stimato del progetto in dollari statunitensi', 'Choose a range': 'Scegli una fascia', 'Project details *': 'Dettagli del progetto *', 'What are you building, improving, or replacing?': 'Cosa vuoi creare, migliorare o sostituire?', 'Current website': 'Sito attuale', 'We only use your information to respond to this inquiry.': 'Usiamo i tuoi dati solo per rispondere a questa richiesta.', 'Sending…': 'Invio…', 'Send project inquiry': 'Invia richiesta',
  'Custom digital products, designed with purpose.': 'Prodotti digitali su misura, progettati con uno scopo.', 'Back to top': 'Torna su', 'All rights reserved.': 'Tutti i diritti riservati.', 'Privacy': 'Privacy', 'Terms': 'Termini', 'Legal links': 'Link legali',
  'Hi! I’m NADAV’s automated assistant. What are you looking to build?': 'Ciao! Sono l’assistente automatico di NADAV. Cosa vorresti realizzare?', 'Open NADAV Assistant': 'Apri l’assistente NADAV', 'Automated FAQ assistant · Available anytime': 'Assistente automatico · Sempre disponibile', 'Contact the team': 'Contatta il team', 'Type your question': 'Scrivi la tua domanda', 'Type your question…': 'Scrivi la tua domanda…', 'Send message': 'Invia messaggio', 'Go to contact': 'Vai ai contatti',
  'Choose a project type and estimated budget.': 'Scegli il tipo di progetto e il budget stimato.', 'We could not send your inquiry. Please try again.': 'Non siamo riusciti a inviare la richiesta. Riprova.', 'Thank you—your inquiry is in. We’ll follow up by email.': 'Grazie, abbiamo ricevuto la richiesta. Ti risponderemo via email.', 'We could not connect. Check your connection and try again.': 'Impossibile connettersi. Controlla la connessione e riprova.', 'Please complete this field.': 'Compila questo campo.', 'Enter a valid email address.': 'Inserisci un indirizzo email valido.', 'Enter a valid phone number.': 'Inserisci un numero di telefono valido.',
  'Not sure yet': 'Non sono ancora sicuro', 'WhatsApp is not available right now. Send your inquiry through the form or email us at {email}.': 'WhatsApp non è disponibile in questo momento. Invia la richiesta dal modulo o scrivici a {email}.',
  'Custom websites': 'Siti web su misura', 'Fast, focused websites built around your business, customers, and goals.': 'Siti veloci e mirati, costruiti intorno alla tua attività, ai clienti e agli obiettivi.', 'Online stores with the catalog, checkout, payments, and management tools you need.': 'Store online con catalogo, checkout, pagamenti e strumenti di gestione.', 'Booking systems': 'Sistemi di prenotazione', 'Branded scheduling experiences for services, staff, availability, and appointments.': 'Prenotazioni personalizzate per servizi, staff, disponibilità e appuntamenti.', 'Restaurant ordering': 'Ordini per ristoranti', 'Custom menus and ordering flows for pickup, delivery, and restaurant operations.': 'Menu e ordini su misura per ritiro, consegna e operatività.', 'Dashboards, workflows, and internal tools shaped around how your team works.': 'Dashboard, flussi di lavoro e strumenti interni modellati sul tuo team.', 'Optimization & support': 'Ottimizzazione e supporto', 'Ongoing improvements, maintenance, and technical support after launch.': 'Miglioramenti, manutenzione e supporto tecnico dopo il lancio.',
  'Booking platform · Custom websites': 'Piattaforma di prenotazione · Siti su misura', 'A custom website and booking experience with services, staff, live availability, appointment scheduling, and business-specific demos.': 'Un sito e un’esperienza di prenotazione su misura con servizi, staff, disponibilità, appuntamenti e demo specifiche.', 'Restaurant ordering · Operations': 'Ordini per ristoranti · Operatività', 'A custom restaurant storefront with menu options, pickup and delivery ordering, stock controls, and tools for managing daily orders.': 'Uno store su misura con opzioni di menu, ordini per ritiro o consegna, controllo scorte e gestione quotidiana.', 'Food & beverage · E-commerce': 'Food & beverage · E-commerce', 'A bold restaurant experience with an online catalog and a direct path to purchase.': 'Un’esperienza food decisa, con catalogo online e un percorso diretto all’acquisto.', 'Craft & services · Business website': 'Artigianato e servizi · Sito aziendale', 'An editorial business site built to explain services, showcase work, and turn visits into inquiries.': 'Un sito editoriale per spiegare i servizi, mostrare i lavori e trasformare le visite in richieste.', 'Fashion · E-commerce': 'Moda · E-commerce', 'An editorial storefront with products, variants, inventory, and connected administration.': 'Uno store editoriale con prodotti, varianti, inventario e amministrazione collegata.', 'Hospitality · Editorial website': 'Hospitality · Sito editoriale', 'A bilingual hospitality website shaped around story, atmosphere, and a direct path to stay inquiries.': 'Un sito hospitality bilingue costruito intorno a racconto, atmosfera e richieste di soggiorno.',
};

export function tr(locale: Locale, value: string) {
  if (locale === 'en') return value;
  return (locale === 'es' ? es : it)[value] ?? value;
}

export function localizedAnswer(locale: Locale, question: string) {
  const value = question.toLowerCase();
  if (locale === 'es') {
    if (/cu[aá]nto|precio|costo|presupuesto/.test(value)) return 'El precio depende del alcance, el contenido, las integraciones y las funciones. Contanos los detalles y te recomendaremos el punto de partida adecuado.';
    if (/tiempo|tarda|plazo|semanas/.test(value)) return 'Los plazos dependen del alcance y de la disponibilidad de contenidos y devoluciones. Antes de empezar definimos un plan de entrega claro.';
    return 'Creamos sitios a medida, tiendas online, sistemas de reservas, pedidos para restaurantes y software para empresas.';
  }
  if (locale === 'it') {
    if (/quanto|prezzo|costo|budget/.test(value)) return 'Il prezzo dipende da ambito, contenuti, integrazioni e funzionalità. Raccontaci il progetto e consiglieremo il punto di partenza più adatto.';
    if (/tempo|durata|settimane/.test(value)) return 'Le tempistiche dipendono dall’ambito e dalla disponibilità di contenuti e feedback. Prima di iniziare definiamo un piano chiaro.';
    return 'Realizziamo siti su misura, e-commerce, sistemi di prenotazione, ordini per ristoranti e software aziendale.';
  }
  if (/price|cost|budget|charge/.test(value)) return 'Pricing depends on scope, content, integrations, and functionality. Share a few project details and we will recommend the right starting point.';
  if (/time|long|timeline|deadline|weeks/.test(value)) return 'Timelines vary by scope and how quickly content and feedback are available. Before work begins, we define a clear delivery plan.';
  return 'We design and build custom websites, e-commerce stores, booking systems, restaurant ordering systems, and business software.';
}

export const quickQuestions: Record<Locale, readonly string[]> = {
  en: ['What does NADAV build?', 'How much does a website cost?', 'How long does a project take?'],
  es: ['¿Qué desarrolla NADAV?', '¿Cuánto cuesta un sitio web?', '¿Cuánto tarda un proyecto?'],
  it: ['Cosa realizza NADAV?', 'Quanto costa un sito web?', 'Quanto dura un progetto?'],
};
