'use client';
import {useEffect,useRef,useState, type ReactNode, type FormEvent} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {ArrowUpRight,ArrowRight,ArrowDown,Menu,X,Plus,Code2,ShoppingBag,Utensils,PanelsTopLeft,Workflow,Wrench,MessageCircle,Send,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {siteConfig,services,faqs,answerQuestion} from './site-config';
import HeroScene from './hero-scene';
const icons=[Code2,ShoppingBag,Utensils,PanelsTopLeft,Workflow,Wrench];
const processSteps=[['Descubrimiento','Entendemos tu negocio, tus objetivos y lo que necesitás.'],['Estrategia','Definimos la estructura, las funcionalidades y la experiencia.'],['Diseño','Damos forma a una identidad visual y una experiencia propia.'],['Desarrollo','Convertimos el diseño en un producto que funciona.'],['Lanzamiento','Publicamos, probamos y optimizamos cada detalle.']];
function Reveal({children,className=''}:{children:ReactNode,className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={{opacity:1,y:0}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:reduced?0:.7}}>{children}</motion.div>}
export default function Home(){const [menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[chat,setChat]=useState(false),[text,setText]=useState(''),[messages,setMessages]=useState([{role:'assistant',text:'¡Hola! Soy el asistente de NADAV. ¿Qué te gustaría crear?'}]),[project,setProject]=useState<number|null>(null),[notice,setNotice]=useState(false),[type,setType]=useState(''),[budget,setBudget]=useState(''),[sending,setSending]=useState(false),[feedback,setFeedback]=useState(''),[success,setSuccess]=useState(false);const chatEnd=useRef<HTMLDivElement>(null);
useEffect(()=>{const update=()=>setScrolled(window.scrollY>30);update();addEventListener('scroll',update,{passive:true});return()=>removeEventListener('scroll',update)},[]);
useEffect(()=>{if(!matchMedia('(pointer: fine)').matches||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const buttons=document.querySelectorAll<HTMLElement>('.button,.nav-cta');const move=(e:PointerEvent)=>{const el=e.currentTarget as HTMLElement;const r=el.getBoundingClientRect();el.style.translate=((e.clientX-r.left-r.width/2)*.06)+'px '+((e.clientY-r.top-r.height/2)*.1)+'px'};const reset=(e:PointerEvent)=>{(e.currentTarget as HTMLElement).style.translate='0px 0px'};buttons.forEach(b=>{b.addEventListener('pointermove',move);b.addEventListener('pointerleave',reset)});return()=>buttons.forEach(b=>{b.removeEventListener('pointermove',move);b.removeEventListener('pointerleave',reset)})},[]);
useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const nodes=document.querySelectorAll('.section-heading, .intro h2, .service');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.1});nodes.forEach(n=>{n.classList.add('reveal-ready');observer.observe(n)});return()=>observer.disconnect()},[]);
useEffect(()=>{chatEnd.current?.scrollIntoView({block:'nearest'})},[messages]);
const whatsapp=siteConfig.whatsapp?`https://wa.me/${siteConfig.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(siteConfig.whatsappMessage)}`:'';
function contactWhatsapp(){if(whatsapp)window.open(whatsapp,'_blank','noopener,noreferrer');else setNotice(true)}
function ask(question:string){if(!question.trim())return;setMessages(m=>[...m,{role:'user',text:question.trim().slice(0,500)},{role:'assistant',text:answerQuestion(question)}]);setText('')}
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(sending)return;const form=e.currentTarget;if(!form.reportValidity())return;if(!type||!budget){setFeedback('Seleccioná el tipo de proyecto y el presupuesto aproximado.');return}setSending(true);setSuccess(false);setFeedback('');const data=Object.fromEntries(new FormData(form));try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,type,budget})});const result=await res.json() as {error?:string};if(!res.ok)throw Error(result.error||'No pudimos enviar tu consulta. Intentá nuevamente.');setSuccess(true);setFeedback('¡Gracias! Recibimos tu consulta. El equipo se pondrá en contacto con vos.');form.reset();setType('');setBudget('')}catch(error){setFeedback(error instanceof Error?error.message:'No pudimos conectar. Revisá tu conexión e intentá nuevamente.')}finally{setSending(false)}}
return <><a href="#contenido" className="skip-link">Ir al contenido</a><header className={scrolled?'nav-shell scrolled':'nav-shell'}><nav aria-label="Navegación principal" className="nav"><a className="wordmark" href="#inicio" aria-label="NADAV inicio">NADAV<span>✳</span></a><div className="nav-links">{['Inicio','Servicios','Proyectos','Contacto'].map(n=><a key={n} href={'#'+n.toLowerCase()}>{n}</a>)}</div><a className="nav-cta" href="#contacto">Hablemos <ArrowUpRight size={15}/></a><button className="menu-toggle" aria-label={menu?'Cerrar menú':'Abrir menú'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>{menu&&<div className="mobile-nav">{['Inicio','Servicios','Proyectos','Contacto'].map(n=><a key={n} href={'#'+n.toLowerCase()} onClick={()=>setMenu(false)}>{n}<ArrowUpRight size={18}/></a>)}</div>}</header>
<main id="contenido"><section id="inicio" className="hero"><div className="hero-copy"><motion.div className="eyebrow" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.6}}><span className="tiny-cross">✳</span> ESTUDIO DE DISEÑO & DESARROLLO</motion.div><h1>Creamos<br/>experiencias<br/>digitales que<br/><span>hacen crecer</span><br/>negocios.</h1><p>Diseño con intención. Tecnología a medida.<br/>Sitios web pensados para convertir<br className="desktop-br"/> visitantes en clientes.</p><div className="hero-actions"><a className="button dark" href="#contacto">Empezar un proyecto <ArrowUpRight size={18}/></a><a className="text-button" href="#proyectos">Ver nuestro trabajo <ArrowRight size={17}/></a></div></div><div className="hero-art"><div className="art-caption">IDEAS SIN LÍMITES.<br/><span>DESARROLLO A MEDIDA.</span></div><HeroScene/><div className="art-foot"><span><i/> DISEÑO × TECNOLOGÍA</span><span>01 — INFINITAS POSIBILIDADES</span></div></div><div className="hero-bottom"><span>Hecho con intención. Desde el primer píxel.</span><a href="#presentacion">Explorá NADAV <ArrowDown size={15}/></a></div></section>
<div className="expertise-strip"><span>DISEÑAMOS LO QUE SIGUE</span><b>Web development</b><Plus/><b>E-commerce</b><Plus/><b>Digital experiences</b><Plus/><b>Custom systems</b></div>
<section id="presentacion" className="intro section-pad"><Reveal><div className="eyebrow">01 / NUESTRA VISIÓN</div><h2>No hacemos páginas web.<br/><span>Construimos herramientas<br/>para negocios.</span></h2><div className="intro-bottom"><span className="asterisk">✳</span><p>Una buena web no solo se ve bien. Trabaja para vos.<br/>En NADAV combinamos diseño, tecnología y estrategia para crear productos digitales que conectan con las personas y resuelven necesidades reales.</p></div></Reveal></section>
<section id="servicios" className="services section-pad"><Reveal><div className="section-heading"><div><div className="eyebrow">02 / LO QUE HACEMOS</div><h2>Todo lo que tu idea<br/>necesita para despegar.</h2></div><p>De la primera impresión<br/>a la última interacción.</p></div><div className="service-grid">{services.map(([title,desc],i)=>{const Icon=icons[i];return <a href="#contacto" onClick={()=>setType(title)} className="service" key={title}><div className="service-top"><Icon size={25} strokeWidth={1.25}/><span>0{i+1}</span></div><h3>{title}</h3><p>{desc}</p><ArrowUpRight className="service-arrow" size={20}/></a>})}</div></Reveal></section>
<section id="proyectos" className="projects section-pad"><Reveal><div className="section-heading"><div><div className="eyebrow">03 / IDEAS EN ACCIÓN</div><h2>Trabajo seleccionado<span className="period">.</span></h2></div><span className="muted small">Dos rubros. Dos experiencias hechas a medida.</span></div><div className="project-grid">{siteConfig.projects.map(p=>{const external=Boolean(p.url);const href=external?p.url:'#contacto';return <article key={p.name} className={'project project-'+p.theme}><a className={'project-visual '+p.theme} href={href} target={external?'_blank':undefined} rel={external?'noopener noreferrer':undefined} aria-label={external?'Ver proyecto '+p.name+' en una nueva pestaña':'Consultar por el proyecto '+p.name}><span className="project-kicker">{p.label}</span>{p.theme==='burgerhouse'?<div className="burgerhouse-preview"><div className="burgerhouse-copy"><span>SMASHED FRESH</span><strong>BURGERS<br/>QUE PEGAN<br/><em>DISTINTO.</em></strong><small>SMASH · CHEESE · REPEAT</small></div><div className="burgerhouse-photo"><img src="/burgerhouse-hero-smash.png" alt="Doble smash cheeseburger de BurgerHouse con cheddar, pepinillos y cebolla" width="1254" height="1254" loading="lazy"/></div><div className="burgerhouse-wordmark">BURGER<span>HOUSE</span></div></div>:<div className="carpimono-preview"><img src="/carpimono-preview.jpg" alt="Portada del sitio Carpimono con un mueble de madera a medida" width="1348" height="926" loading="lazy"/><span className="preview-browser"><i/><i/><i/><b>webcarpimono.vercel.app</b></span></div>}<span className="project-open"><ArrowUpRight size={22}/></span></a><div className="project-info"><div><span className="category">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p></div><a className={'view-project'+(external?'':' is-pending')} href={href} target={external?'_blank':undefined} rel={external?'noopener noreferrer':undefined}>{external?'Ver proyecto':'URL próximamente'} <ArrowUpRight size={16}/></a></div></article>})}</div></Reveal></section>
<section id="proceso" className="process section-pad"><div className="process-intro"><div className="eyebrow">04 / CÓMO TRABAJAMOS</div><h2>De una idea<br/>a un producto<br/><span>real.</span></h2><p>Un proceso claro.<br/>Una conversación constante.<br/>Un resultado pensado para vos.</p><a href="#contacto" className="text-button">Construyamos algo juntos <ArrowUpRight size={18}/></a></div><div className="steps">{processSteps.map(([title,desc],i)=><motion.div initial={{borderColor:'#303136'}} whileInView={{borderColor:'#b1b4bb'}} viewport={{once:true,amount:.8}} className="step" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div><Plus size={18}/></motion.div>)}</div></section>
<section id="contacto" className="contact section-pad"><div className="contact-copy"><div className="eyebrow">05 / EL PRÓXIMO PASO</div><h2>¿Tenés una idea?<br/><span>Hagámosla<br/>realidad.</span></h2><p>Contanos qué necesitás y te ayudamos a<br/>convertirlo en un producto digital.</p><button className="button dark" onClick={contactWhatsapp}>Hablar por WhatsApp <ArrowUpRight size={19}/></button><div className="contact-note"><span>Una buena conversación puede<br/>ser el comienzo de algo grande.</span><span className="asterisk">✳</span></div></div><form onSubmit={submit} className="contact-form"><h3>Contanos sobre tu proyecto.</h3><div className="form-grid"><label>Nombre *<input required name="name" autoComplete="name" minLength={2} maxLength={100} placeholder="Tu nombre"/></label><label>Empresa<input name="company" autoComplete="organization" maxLength={150} placeholder="Nombre de tu negocio"/></label><label>Email *<input required type="email" name="email" autoComplete="email" maxLength={150} placeholder="vos@empresa.com"/></label><label>WhatsApp<input type="tel" name="phone" autoComplete="tel" pattern="[+0-9 ()-]{6,25}" maxLength={25} placeholder="+54 9 ..."/></label><label>Tipo de proyecto *<Select value={type} onValueChange={setType}><SelectTrigger className="form-select" aria-label="Tipo de proyecto"><SelectValue placeholder="¿Qué necesitás?"/></SelectTrigger><SelectContent>{services.map(([s])=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label><label>Presupuesto aproximado *<Select value={budget} onValueChange={setBudget}><SelectTrigger className="form-select" aria-label="Presupuesto aproximado"><SelectValue placeholder="Elegí un rango"/></SelectTrigger><SelectContent>{['Menos de USD 500','USD 500 – 1.500','USD 1.500 – 3.000','Más de USD 3.000','A definir juntos'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label><label className="full">Mensaje *<textarea name="message" required minLength={10} maxLength={4000} rows={3} placeholder="Tu idea, tus objetivos, eso que querés mejorar..."/></label><label className="honeypot" aria-hidden="true">Sitio actual<input name="website" tabIndex={-1} autoComplete="off"/></label></div><p className="privacy-note">Usaremos tus datos únicamente para responder a tu consulta.</p><button className="button submit" disabled={sending}>{sending?'Enviando...':'Enviar consulta'} {success?<Check size={18}/>:<ArrowUpRight size={18}/>}</button>{feedback&&<p role="status" className={success?'feedback success':'feedback'}>{feedback}</p>}</form></section>
</main><footer><div className="footer-top"><a href="#inicio" className="wordmark">NADAV<span>✳</span></a><p>Diseño con intención. Desarrollo sin límites.</p><a href="#inicio" className="back-top">Volver arriba <ArrowUpRight size={16}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} NADAV. Todos los derechos reservados.</span><span>DISEÑO × TECNOLOGÍA</span></div><div className="footer-credits">Dante Carrizo &amp; Gonzalo Gaitan</div></footer>
<div className="floating"><button className="whatsapp-float" onClick={contactWhatsapp} aria-label="Hablemos por WhatsApp"><MessageCircle size={20}/><span>Hablemos por WhatsApp</span></button><button className="chat-launch" onClick={()=>setChat(!chat)} aria-expanded={chat} aria-label="Abrir Nadav Assistant"><span className="assistant-symbol">✳</span><span>Nadav Assistant</span>{chat?<X size={16}/>:<Plus size={16}/>}</button></div>
<Dialog open={chat} onOpenChange={setChat}><DialogContent className="chat-panel"><DialogTitle className="chat-title"><span className="assistant-symbol">✳</span> Nadav Assistant</DialogTitle><DialogDescription className="chat-subtitle">Asistente automático · Disponible 24/7</DialogDescription><div className="chat-messages" role="log" aria-live="polite">{messages.map((m,i)=><div key={i} className={'bubble '+m.role}>{m.text}</div>)}<div ref={chatEnd}/></div><div className="quick-questions">{faqs.slice(0,3).map(f=><button key={f.q} onClick={()=>ask(f.q)}>{f.q}</button>)}</div><a className="chat-contact" href="#contacto" onClick={()=>setChat(false)}>Contactar con el equipo <ArrowUpRight size={14}/></a><form className="chat-input" onSubmit={e=>{e.preventDefault();ask(text)}}><input autoComplete="off" aria-label="Escribí tu consulta" placeholder="Escribí tu consulta..." maxLength={500} value={text} onChange={e=>setText(e.target.value)}/><button type="submit" disabled={!text.trim()} aria-label="Enviar mensaje"><Send size={18}/></button></form></DialogContent></Dialog>
<Dialog open={project!==null} onOpenChange={open=>{if(!open)setProject(null)}}><DialogContent className="project-modal"><DialogTitle>{project!==null&&siteConfig.projects[project].name}</DialogTitle><DialogDescription>{project!==null&&siteConfig.projects[project].category} · Concepto demo</DialogDescription>{project!==null&&<><p>{siteConfig.projects[project].details}</p><div className="tags">{siteConfig.projects[project].technologies.map(t=><span key={t}>{t}</span>)}</div>{siteConfig.projects[project].url?<a className="button dark" target="_blank" rel="noopener noreferrer" href={siteConfig.projects[project].url}>Abrir sitio <ArrowUpRight size={18}/></a>:<a className="button dark" href="#contacto" onClick={()=>setProject(null)}>Quiero un proyecto así <ArrowUpRight size={18}/></a>}</>}</DialogContent></Dialog>
<Dialog open={notice} onOpenChange={setNotice}><DialogContent><DialogTitle>Hablemos de tu idea</DialogTitle><DialogDescription>El canal de WhatsApp todavía no está habilitado. Podés preparar tu consulta en el formulario de contacto.</DialogDescription><a className="button dark" href="#contacto" onClick={()=>setNotice(false)}>Ir a contacto <ArrowUpRight size={18}/></a></DialogContent></Dialog>
</>}
